import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";
import "./globals.css";

const johnstonitcstd = localFont({
  src: [
    {
      path: "./assets/fonts/johnstonitcstd-medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/johnstonitcstd-lightItalic.woff2",
      weight: "200",
      style: "italic",
    },
    {
      path: "./assets/fonts/johnstonitcstd-light.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "./assets/fonts/johnstonitcstd-bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={johnstonitcstd.className}>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  );
}
